services:
  - type: web
    name: dank-springboot-app
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/dank-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: MONGODB_URI
        value: mongodb://your-hostname:27017/mydb
    healthCheckPath: /actuator/health
    autoDeploy: true
