services:
- type: web
  name: RESTApis
  runtime: docker
  repo: https://github.com/mounikawgsindia/RESTApis
  plan: free
  envVars:
  - key: SPRING_DATA_MONGODB_URI
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
version: "1"
